version: "3.4"
services:

  gphoto-sync:
    image: golenski/gphoto-sync:0.2.1
    container_name: gphoto-sync
    env_file:
      - .env
    volumes:
      - ${PHOTO_GOOGLE_CREDENTIAL_DIR}:${PHOTO_GOOGLE_CREDENTIAL_DIR}
      - ${PHOTO_LIBRARY_PATH}:${PHOTO_LIBRARY_PATH}
    ports:
    - ${PHOTO_GOOGLE_RECEIVER_PORT}:${PHOTO_GOOGLE_RECEIVER_PORT}