name: verify
on: push

jobs:
  verify:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install dependencies
        run: mvn dependency:go-offline
      - name: Run test suites
        run: mvn --batch-mode clean verify